server:
  port: 8080
spring:
  cloud:
    gateway:
#      default-filters:
#        - name: LogFilter
      routes:
        - id: catalogRoute
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
#          filters:
#            - name: SubscriptionFilter
        - id: movieRoute
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie/**
#          filters:
#            - AddRequestHeader=course-request-header, custom-course-request-header
#            - AddResponseHeader=course-response-header, custom-course-response-header
