spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: movie-service-dev
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/locadora
      username: postgres
      password: ruan
      driverClassName: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/locadora/movie
    user: postgres
    password: ruan
    locations: classpath:db/migration
